apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eightbitsaxlounge-chat-tokens
  labels:
    app: eightbitsaxlounge
    component: chat
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
