---
- name: Deploy MIDI API to Windows PC
  hosts: midi-host
  gather_facts: true
  vars:
    deploy_base: "C:\\Services\\Midi"
    service_name_dev: "MidiApi-Dev"
    service_name_prod: "MidiApi-Prod"

  tasks:
    - name: Set deployment variables based on environment
      ansible.builtin.set_fact:
        target_dir: "{{ deploy_base }}\\{{ lookup('env', 'ENVIRONMENT') }}"
        service_name: "{{ service_name_dev if lookup('env', 'ENVIRONMENT') == 'dev' else service_name_prod }}"
        service_port: "{{ '5000' if lookup('env', 'ENVIRONMENT') == 'dev' else '5001' }}"
        version: "{{ lookup('env', 'VERSION') }}"
        artifact_path: "{{ lookup('env', 'ARTIFACT_PATH') }}"
        version_changed: "{{ lookup('env', 'NEEDS_BUILD') | default('true') }}"

    - name: Display deployment info
      ansible.builtin.debug:
        msg:
          - "Deploying MIDI API version {{ version }}"
          - "Environment: {{ lookup('env', 'ENVIRONMENT') }}"
          - "Target directory: {{ target_dir }}"
          - "Service name: {{ service_name }}"
          - "Service port: {{ service_port }}"
          - "Version changed: {{ version_changed }}"
          - "Deployment type: {{ 'Full (new version)' if version_changed == 'true' else 'Config-only (existing version)' }}"

    # ========== Stop Service ==========
    - name: Check if service exists
      ansible.windows.win_shell: |
        $nssm = "C:\Tools\nssm\nssm.exe"
        & $nssm status "{{ service_name }}" 2>$null
        exit $LASTEXITCODE
      register: service_exists
      failed_when: false
      changed_when: false

    - name: Stop service if it exists
      ansible.windows.win_service:
        name: "{{ service_name }}"
        state: stopped
      when: service_exists.rc == 0
      register: service_stop
      failed_when: false

    # ========== Deploy Artifact ==========
    - name: Create version-specific directory
      ansible.windows.win_file:
        path: "{{ target_dir }}\\{{ version }}"
        state: directory
      when: version_changed == 'true'

    - name: Copy artifact to Windows PC
      ansible.windows.win_copy:
        src: "{{ artifact_path }}"
        dest: "{{ target_dir }}\\midi-api-{{ version }}.tar.gz"
      when: version_changed == 'true'

    - name: Extract artifact
      ansible.windows.win_shell: |
        tar -xzf "{{ target_dir }}\midi-api-{{ version }}.tar.gz" -C "{{ target_dir }}\{{ version }}"
      args:
        creates: "{{ target_dir }}\\{{ version }}\\NineteenSeventyTwo.EightBitSaxLounge.Midi.MinimalApi.exe"
      when: version_changed == 'true'

    - name: Update current symlink
      ansible.windows.win_shell: |
        $linkPath = "{{ target_dir }}\current"
        if (Test-Path $linkPath) {
          Remove-Item $linkPath -Force -Recurse -Confirm:$false
        }
        New-Item -ItemType SymbolicLink -Path $linkPath -Target "{{ target_dir }}\{{ version }}" -Force | Out-Null
        Write-Output "Symlink updated to version {{ version }}"
      when: version_changed == 'true'

    # ========== Configure Service ==========
    - name: Install/update service with NSSM
      ansible.windows.win_shell: |
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $nssm = "C:\Tools\nssm\nssm.exe"
        $service = "{{ service_name }}"
        $exe = "{{ target_dir }}\current\NineteenSeventyTwo.EightBitSaxLounge.Midi.MinimalApi.exe"
        
        # Build environment variables array
        $envVars = @(
          "ASPNETCORE_URLS=http://0.0.0.0:{{ service_port }}"
          "ASPNETCORE_ENVIRONMENT={{ lookup('env', 'ENVIRONMENT') | upper }}"
          "ConnectionStrings__EightBitSaxLoungeDataLayer={{ lookup('env', 'CONNECTIONSTRINGS__EIGHTBITSAXLOUNGEDATALAYER') }}"
          "Authentication__TokenExpiryInMinutes={{ lookup('env', 'AUTHENTICATION__TOKENEXPIRYINMINUTES') }}"
          "Authentication__SecretKey={{ lookup('env', 'AUTHENTICATION__SECRETKEY') }}"
          "Authentication__Issuer={{ lookup('env', 'AUTHENTICATION__ISSUER') }}"
          "Authentication__Audience={{ lookup('env', 'AUTHENTICATION__AUDIENCE') }}"
          "Authentication__Clients__0__ClientId={{ lookup('env', 'AUTHENTICATION__CLIENTS__0__CLIENTID') }}"
          "Authentication__Clients__0__ClientSecret={{ lookup('env', 'AUTHENTICATION__CLIENTS__0__CLIENTSECRET') }}"
          "Authentication__Clients__1__ClientId={{ lookup('env', 'AUTHENTICATION__CLIENTS__1__CLIENTID') }}"
          "Authentication__Clients__1__ClientSecret={{ lookup('env', 'AUTHENTICATION__CLIENTS__1__CLIENTSECRET') }}"
          "MidiDeviceService__BypassKey={{ lookup('env', 'MIDIDEVICESERVICE__BYPASSKEY') }}"
        )
        
        # Check if service exists
        $exists = & $nssm status $service 2>$null
        
        if ($LASTEXITCODE -ne 0) {
          # Install new service
          & $nssm install $service $exe | Out-Null
          & $nssm set $service AppDirectory "{{ target_dir }}\current" | Out-Null
          & $nssm set $service DisplayName "MIDI API ({{ lookup('env', 'ENVIRONMENT') | upper }})" | Out-Null
          & $nssm set $service Description "NineteenSeventyTwo MIDI API - {{ lookup('env', 'ENVIRONMENT') }} environment" | Out-Null
          & $nssm set $service Start SERVICE_AUTO_START | Out-Null
          & $nssm set $service AppStdout "{{ deploy_base }}\logs\{{ service_name }}-stdout.log" | Out-Null
          & $nssm set $service AppStderr "{{ deploy_base }}\logs\{{ service_name }}-stderr.log" | Out-Null
          
          # Set environment variables
          & $nssm set $service AppEnvironmentExtra ($envVars -join "`r`n") | Out-Null
          
          Write-Output "Service installed successfully"
        } else {
          # Update existing service
          & $nssm set $service Application $exe | Out-Null
          & $nssm set $service AppDirectory "{{ target_dir }}\current" | Out-Null
          
          # Reset and set environment variables
          & $nssm reset $service AppEnvironmentExtra | Out-Null
          & $nssm set $service AppEnvironmentExtra ($envVars -join "`r`n") | Out-Null
          
          Write-Output "Service updated successfully"
        }
      register: nssm_result

    - name: Print NSSM result
      ansible.builtin.debug:
        msg: "{{ nssm_result.stdout | trim }}"

    # ========== Start Service ==========
    - name: Start service
      ansible.windows.win_service:
        name: "{{ service_name }}"
        state: started

    - name: Wait for service to be ready
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ service_port }}"
        delay: 5
        timeout: 60
      delegate_to: localhost

    # ========== Verify Deployment ==========
    - name: Check service status
      ansible.windows.win_service:
        name: "{{ service_name }}"
      register: final_service_check

    - name: Verify API is responding
      ansible.builtin.uri:
        url: "http://{{ ansible_host }}:{{ service_port }}/"
        method: OPTIONS
        status_code: [200, 204]
        timeout: 10
      delegate_to: localhost
      register: health_check
      failed_when: false

    # ========== Summary ==========
    - name: Print deployment summary
      ansible.builtin.debug:
        msg:
          - "========== Deployment Complete =========="
          - "Version: {{ version }}"
          - "Environment: {{ lookup('env', 'ENVIRONMENT') }}"
          - "Service: {{ service_name }}"
          - "Status: {{ final_service_check.state }}"
          - "Port: {{ service_port }}"
          - "Health check: {{ 'PASSED' if health_check.status in [200, 204] else 'FAILED' }}"
          - "URL: http://{{ ansible_host }}:{{ service_port }}"
          - "========================================"
