---
- name: Send SetEffect Request to MIDI Service
  hosts: master
  vars:
    k8s_namespace: "{{ lookup('env', 'NAMESPACE') | default('eightbitsaxlounge-dev', true) }}"
    auth_client_id: "{{ lookup('env', 'AUTH_CLIENT_0_ID') }}"
    auth_client_secret: "{{ lookup('env', 'AUTH_CLIENT_0_SECRET') }}"
    device: "{{ lookup('env', 'DEVICE') }}"
    device_effect: "{{ lookup('env', 'DEVICE_EFFECT') }}"
    device_effect_setting: "{{ lookup('env', 'DEVICE_EFFECT_SETTING') }}"
    value: "{{ lookup('env', 'VALUE') | default('', true) }}"
    selection: "{{ lookup('env', 'SELECTION') | default('', true) }}"

  tasks:
    - name: Validate required parameters
      ansible.builtin.fail:
        msg: "Required parameter missing: {{ item }}"
      when: vars[item] is not defined or vars[item] == ""
      loop:
        - device
        - device_effect
        - device_effect_setting

    - name: Get MIDI service details
      ansible.builtin.shell: |
        kubectl get svc -n {{ k8s_namespace }} -l app=eightbitsaxlounge,component=midi -o jsonpath='{.items[0].metadata.name}'
      register: service_name_result
      failed_when: service_name_result.stdout == ""

    - name: Get service cluster IP
      ansible.builtin.shell: |
        kubectl get svc -n {{ k8s_namespace }} {{ service_name_result.stdout }} -o jsonpath='{.spec.clusterIP}'
      register: service_ip_result

    - name: Set service URL
      ansible.builtin.set_fact:
        service_url: "http://{{ service_ip_result.stdout }}:8080"

    - name: Request authentication token
      ansible.builtin.uri:
        url: "{{ service_url }}/api/token"
        method: POST
        body_format: json
        body:
          clientId: "{{ auth_client_id }}"
          clientSecret: "{{ auth_client_secret }}"
        status_code: [200, 201]
        return_content: yes
      register: token_response
      no_log: true
      failed_when: false

    - name: Show token request error
      ansible.builtin.debug:
        msg: |
          Token request failed!
          Status: {{ token_response.status | default('N/A') }}
          Message: {{ token_response.msg | default('N/A') }}
      when: token_response.status is defined and token_response.status not in [200, 201]

    - name: Fail on token request error
      ansible.builtin.fail:
        msg: "Failed to obtain authentication token. See error above."
      when: token_response.status is defined and token_response.status not in [200, 201]

    - name: Debug token response structure
      ansible.builtin.debug:
        msg: "Token response: {{ token_response.json }}"
      when: token_response.status in [200, 201]

    - name: Parse token from response
      ansible.builtin.set_fact:
        auth_token: "{{ token_response.json.access_token }}"
      when: token_response.status in [200, 201]

    - name: Verify token was parsed
      ansible.builtin.fail:
        msg: "Token not found in response. Check response structure above."
      when: auth_token is not defined or auth_token == ""

    - name: Build request body
      ansible.builtin.set_fact:
        request_body: "{{ request_body | default({}) | combine({item.key: item.value}) }}"
      when: item.value != ""
      loop:
        - { key: 'deviceName', value: '{{ device }}' }
        - { key: 'deviceEffectName', value: '{{ device_effect }}' }
        - { key: 'deviceEffectSettingName', value: '{{ device_effect_setting }}' }
        - { key: 'value', value: '{{ value | int if value != "" else "" }}' }
        - { key: 'selection', value: '{{ selection }}' }

    - name: Display request parameters
      ansible.builtin.debug:
        msg: |
          Sending SetEffect request:
          Device: {{ device }}
          Device Effect: {{ device_effect }}
          Device Effect Setting: {{ device_effect_setting }}
          Value: {{ value if value != "" else "not provided" }}
          Selection: {{ selection if selection != "" else "not provided" }}

    - name: Send SetEffect request
      ansible.builtin.uri:
        url: "{{ service_url }}/api/Midi/SetEffect"
        method: POST
        headers:
          Authorization: "Bearer {{ auth_token }}"
          Content-Type: "application/json"
        body_format: json
        body: "{{ request_body }}"
        status_code: [200, 201, 204]
        return_content: yes
      register: seteffect_result

    - name: Display SetEffect result
      ansible.builtin.debug:
        msg: "SetEffect request completed successfully (HTTP {{ seteffect_result.status }})"

    - name: Display response body on success
      ansible.builtin.debug:
        msg: "{{ seteffect_result.content }}"
      when: seteffect_result.content is defined and seteffect_result.content | length > 0
