---
- name: Deploy Eightbitsaxlounge MIDI API on Kubernetes
  hosts: master
  tasks:
    - name: Ensure required environment variables are provided
      ansible.builtin.assert:
        that:
          - lookup('env','NAMESPACE') | length > 0
          - lookup('env','VERSION') | length > 0
        fail_msg: "Missing required env vars: NAMESPACE and/or VERSION"

    - name: Display deployment info
      ansible.builtin.debug:
        msg:
          - "Deploying MIDI API version {{ lookup('env', 'VERSION') }}"
          - "Namespace: {{ lookup('env', 'NAMESPACE') }}"
          - "Version changed: {{ lookup('env', 'NEEDS_BUILD') | default('true') }}"
          - "Deployment type: {{ 'Full (new container)' if lookup('env', 'NEEDS_BUILD') | default('true') == 'true' else 'Config-only (existing container)' }}"

    - name: Create a temporary directory for manifests
      ansible.builtin.tempfile:
        state: directory
        suffix: midi-k8s
      register: tempdir

    - name: Copy manifests to temp directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ tempdir.path }}/{{ item | basename }}"
      loop:
        - k8s/deployment.yaml
        - k8s/service.yaml

    - name: Debug CONNECTION_STRING before creating secret
      ansible.builtin.debug:
        msg: "CONNECTION_STRING from env: {{ lookup('env', 'CONNECTION_STRING') }}"

    - name: Create MIDI Secrets
      ansible.builtin.shell: |
        kubectl create secret generic eightbitsaxlounge-midi-secrets \
          --from-literal=secret-key="$AUTH_SECRET_KEY" \
          --from-literal=issuer="$AUTH_ISSUER" \
          --from-literal=audience="$AUTH_AUDIENCE" \
          --from-literal=client-0-id="$AUTH_CLIENT_0_ID" \
          --from-literal=client-0-secret="$AUTH_CLIENT_0_SECRET" \
          --from-literal=client-1-id="$AUTH_CLIENT_1_ID" \
          --from-literal=client-1-secret="$AUTH_CLIENT_1_SECRET" \
          --from-literal=connection-string="$CONNECTION_STRING" \
          --from-literal=device-bypass-key="$DEVICE_BYPASS_KEY" \
          --namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -
      environment:
        AUTH_SECRET_KEY: "{{ lookup('env', 'AUTH_SECRET_KEY') }}"
        AUTH_ISSUER: "{{ lookup('env', 'AUTH_ISSUER') }}"
        AUTH_AUDIENCE: "{{ lookup('env', 'AUTH_AUDIENCE') }}"
        AUTH_CLIENT_0_ID: "{{ lookup('env', 'AUTH_CLIENT_0_ID') }}"
        AUTH_CLIENT_0_SECRET: "{{ lookup('env', 'AUTH_CLIENT_0_SECRET') }}"
        AUTH_CLIENT_1_ID: "{{ lookup('env', 'AUTH_CLIENT_1_ID') }}"
        AUTH_CLIENT_1_SECRET: "{{ lookup('env', 'AUTH_CLIENT_1_SECRET') }}"
        CONNECTION_STRING: "{{ lookup('env', 'CONNECTION_STRING') }}"
        DEVICE_BYPASS_KEY: "{{ lookup('env', 'DEVICE_BYPASS_KEY') }}"
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Create MIDI ConfigMap
      ansible.builtin.shell: |
        kubectl create configmap eightbitsaxlounge-midi-config \
          --from-literal=device_service_url="$DEVICE_SERVICE_URL" \
          --from-literal=token_expiry_minutes="$TOKEN_EXPIRY" \
          --namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -
      environment:
        DEVICE_SERVICE_URL: "{{ lookup('env', 'DEVICE_SERVICE_URL') }}"
        TOKEN_EXPIRY: "{{ lookup('env', 'TOKEN_EXPIRY') | default('60', true) }}"
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Deploy MIDI Service
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/service.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Deploy MIDI Deployment
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/deployment.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Patch Deployment image to versioned tag
      ansible.builtin.shell: |
        IMAGE_BASE=${IMAGE_BASE:-ghcr.io/${GITHUB_REPOSITORY_OWNER}/eightbitsaxlounge-midi}
        kubectl -n "$NAMESPACE" set image deploy/eightbitsaxlounge-midi \
          midi-api="${IMAGE_BASE}:${VERSION}"
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
        VERSION: "{{ lookup('env', 'VERSION') }}"
        GITHUB_REPOSITORY_OWNER: "{{ lookup('env', 'GITHUB_REPOSITORY_OWNER') | default('', true) }}"
        IMAGE_BASE: "{{ lookup('env', 'IMAGE_BASE') | default('', true) }}"

    - name: Annotate Deployment with change cause
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" annotate deploy/eightbitsaxlounge-midi \
          kubernetes.io/change-cause="midi-api ${VERSION}" --overwrite
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
        VERSION: "{{ lookup('env', 'VERSION') }}"

    - name: Restart deployment to pickup changes
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" rollout restart deployment/eightbitsaxlounge-midi
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Wait for rollout to complete
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" rollout status deploy/eightbitsaxlounge-midi --timeout=180s
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Verify running image
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" get deploy eightbitsaxlounge-midi -o jsonpath='{.spec.template.spec.containers[0].image}'
      register: deploy_image
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Print running image
      ansible.builtin.debug:
        msg: "Deployment image: {{ deploy_image.stdout }}"

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent
