---
- name: Initialize MIDI Datamodel
  hosts: master
  vars:
    k8s_namespace: "{{ lookup('env', 'NAMESPACE') | default('eightbitsaxlounge-dev', true) }}"
    auth_client_id: "{{ lookup('env', 'AUTH_CLIENT_0_ID') }}"
    auth_client_secret: "{{ lookup('env', 'AUTH_CLIENT_0_SECRET') }}"
    service_url: "http://eightbitsaxlounge-midi-service.{{ k8s_namespace }}.svc.cluster.local:8080"

  tasks:
    - name: Request authentication token
      ansible.builtin.uri:
        url: "{{ service_url }}/api/token"
        method: POST
        body_format: json
        body:
          clientId: "{{ auth_client_id }}"
          clientSecret: "{{ auth_client_secret }}"
        status_code: [200, 201]
        return_content: yes
      register: token_response
      no_log: true
      failed_when: false

    - name: Show token request error
      ansible.builtin.debug:
        msg: |
          Token request failed!
          Status: {{ token_response.status | default('N/A') }}
          Message: {{ token_response.msg | default('N/A') }}
      when: token_response.status is defined and token_response.status not in [200, 201]

    - name: Fail on token request error
      ansible.builtin.fail:
        msg: "Failed to obtain authentication token. See error above."
      when: token_response.status is defined and token_response.status not in [200, 201]

    - name: Parse token from response
      ansible.builtin.set_fact:
        auth_token: "{{ token_response.json.token }}"
      no_log: true

    - name: Initialize datamodel
      ansible.builtin.uri:
        url: "{{ service_url }}/api/Midi/InitDatamodel"
        method: POST
        headers:
          Authorization: "Bearer {{ auth_token }}"
        status_code: [200, 201, 204]
        return_content: yes
      register: init_result

    - name: Display initialization result
      ansible.builtin.debug:
        msg: "Datamodel initialization completed successfully (HTTP {{ init_result.status }})"

    - name: Display response body on success
      ansible.builtin.debug:
        msg: "{{ init_result.content }}"
      when: init_result.content | length > 0
