---
- name: Deploy Security Scanner to Kubernetes
  hosts: master
  tasks:
    - name: Ensure required environment variables are provided
      ansible.builtin.assert:
        that:
          - lookup('env','NAMESPACE') | length > 0
          - lookup('env','VERSION') | length > 0
        fail_msg: "Missing required env vars: NAMESPACE and/or VERSION"

    - name: Display deployment info
      ansible.builtin.debug:
        msg:
          - "Deploying Security scanner version {{ lookup('env', 'VERSION') }}"
          - "Namespace: {{ lookup('env', 'NAMESPACE') }}"

    - name: Create a temporary directory for manifests
      ansible.builtin.tempfile:
        state: directory
        suffix: security-k8s
      register: tempdir

    - name: Template CronJob manifest to temp directory
      ansible.builtin.template:
        src: k8s/cronjob.yaml.j2
        dest: "{{ tempdir.path }}/cronjob.yaml"

    - name: Create security scan secret (holds GitHub PAT for SARIF upload)
      ansible.builtin.shell: |
        kubectl create secret generic security-scan-secret \
          --from-literal=github_pat=$GITHUB_PAT \
          --namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -
      environment:
        GITHUB_PAT: "{{ lookup('env', 'GITHUB_PAT') }}"
        NAMESPACE: "{{ lookup('env','NAMESPACE') }}"

    - name: Copy PVC manifest to temp directory
      ansible.builtin.copy:
        src: k8s/persistentvolumeclaim.yaml
        dest: "{{ tempdir.path }}/persistentvolumeclaim.yaml"

    - name: Deploy PVC
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/persistentvolumeclaim.yaml
      environment:
        NAMESPACE: "{{ lookup('env','NAMESPACE') }}"

    - name: Deploy CronJob
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/cronjob.yaml
      environment:
        NAMESPACE: "{{ lookup('env','NAMESPACE') }}"

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent
