apiVersion: v1
kind: DaemonSet
metadata:
  name: longhorn-iscsi-installation
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: longhorn-iscsi-installation
  template:
    metadata:
      labels:
        app: longhorn-iscsi-installation
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: iscsi-installer
        image: ubuntu:22.04
        command:
        - /bin/bash
        - -c
        - |
          apt-get update
          apt-get install -y open-iscsi nfs-common
          systemctl enable iscsid || true
          systemctl start iscsid || true
          echo "iSCSI installation complete on $(hostname)"
          sleep infinity
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
