---
- name: Initialize Console Configuration
  hosts: localhost
  become: true
  tasks:
    - name: Ensure /etc/ansible exists and is owned by root
      file:
        path: /etc/ansible
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Install ansible.cfg from template
      template:
        src: ansible.cfg.j2
        dest: /etc/ansible/ansible.cfg
        owner: root
        group: root
        mode: '0644'

    - name: Install ansiblehosts.j2 template
      template:
        src: ansiblehosts.j2
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: '0644'

  roles:
    - name: dhcp