---
- name: Initialize Console Configuration
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Install ansiblehosts.j2 template
      template:
        src: ansiblehosts.j2
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: '0644'