---
- name: Deploy Grafana Kubernetes Monitoring
  hosts: master
  become: false
  vars:
    grafana_cluster: nineteenseventytwo 

  tasks:
    - name: Check if Helm is installed
      ansible.builtin.command:
        cmd: helm version
      register: helm_check
      ignore_errors: true

    - name: Include Helm role if Helm is not installed
      include_role:
        name: helm
      when: helm_check.rc != 0

    - name: Add Grafana Helm repository
      ansible.builtin.shell:
        cmd: helm repo add grafana https://grafana.github.io/helm-charts
    
    - name: Update Helm repositories
      ansible.builtin.shell:
        cmd: helm repo update

    - name: Install Alloy CRD
      ansible.builtin.command:
        cmd: kubectl apply -f https://github.com/grafana/alloy-operator/releases/download/v0.2.9/collectors.grafana.com_alloy.yaml

    - name: Wait for Alloy CRD to be established
      ansible.builtin.command:
        cmd: kubectl get crd alloys.collectors.grafana.com
      register: crd_check
      retries: 10
      delay: 3
      until: crd_check.rc == 0

    - name: Install or upgrade Grafana Kubernetes Monitoring
      ansible.builtin.command:
        cmd: >
          helm upgrade --install --rollback-on-failure --timeout 300s grafana-k8s-monitoring grafana/k8s-monitoring
          --namespace "monitoring" --create-namespace --values -
      args:
        stdin: |
          cluster:
            name: {{grafana_cluster}}
          destinations:
            - name: grafana-cloud-metrics
              type: prometheus
              url: https://prometheus-prod-55-prod-gb-south-1.grafana.net./api/prom/push
              auth:
                type: basic
                username: "2374961"
                password: "{{ grafana_password }}"
            - name: grafana-cloud-logs
              type: loki
              url: https://logs-prod-035.grafana.net./loki/api/v1/push
              auth:
                type: basic
                username: "1183158"
                password: "{{ grafana_password }}"
            - name: gc-otlp-endpoint
              type: otlp
              url: https://otlp-gateway-prod-gb-south-1.grafana.net./otlp
              protocol: http
              auth:
                type: basic
                username: "1225361"
                password: "{{ grafana_password }}"
              metrics:
                enabled: true
              logs:
                enabled: true
              traces:
                enabled: true
          clusterMetrics:
            enabled: true
            opencost:
              enabled: true
              metricsSource: grafana-cloud-metrics
              opencost:
                exporter:
                  defaultClusterId: {{grafana_cluster}}
                prometheus:
                  existingSecretName: grafana-cloud-metrics-grafana-k8s-monitoring
                  external:
                    url: https://prometheus-prod-55-prod-gb-south-1.grafana.net./api/prom
            kepler:
              enabled: true
          clusterEvents:
            enabled: true
          podLogs:
            enabled: true
          applicationObservability:
            enabled: true
            receivers:
              otlp:
                grpc:
                  enabled: true
                  port: 4317
                http:
                  enabled: true
                  port: 4318
              zipkin:
                enabled: true
                port: 9411
          alloy-metrics:
            enabled: true
            alloy:
              extraEnv:
                - name: GCLOUD_RW_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: alloy-metrics-remote-cfg-grafana-k8s-monitoring
                      key: password
                - name: CLUSTER_NAME
                  value: {{grafana_cluster}}
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-023.grafana.net
              auth:
                type: basic
                username: "1225361"
                password: "{{ grafana_password }}"
          alloy-singleton:
            enabled: true
            alloy:
              extraEnv:
                - name: GCLOUD_RW_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: alloy-singleton-remote-cfg-grafana-k8s-monitoring
                      key: password
                - name: CLUSTER_NAME
                  value: {{grafana_cluster}}
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-$(POD_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-023.grafana.net
              auth:
                type: basic
                username: "1225361"
                password: "{{ grafana_password }}"
          alloy-logs:
            enabled: true
            alloy:
              extraEnv:
                - name: GCLOUD_RW_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: alloy-logs-remote-cfg-grafana-k8s-monitoring
                      key: password
                - name: CLUSTER_NAME
                  value: {{grafana_cluster}}
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-logs-$(NODE_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-023.grafana.net
              auth:
                type: basic
                username: "1225361"
                password: "{{ grafana_password }}"
          alloy-receiver:
            enabled: true
            alloy:
              extraPorts:
                - name: otlp-grpc
                  port: 4317
                  targetPort: 4317
                  protocol: TCP
                - name: otlp-http
                  port: 4318
                  targetPort: 4318
                  protocol: TCP
                - name: zipkin
                  port: 9411
                  targetPort: 9411
                  protocol: TCP
              extraEnv:
                - name: GCLOUD_RW_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: alloy-receiver-remote-cfg-grafana-k8s-monitoring
                      key: password
                - name: CLUSTER_NAME
                  value: {{grafana_cluster}}
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: GCLOUD_FM_COLLECTOR_ID
                  value: grafana-k8s-monitoring-$(CLUSTER_NAME)-$(NAMESPACE)-alloy-receiver-$(NODE_NAME)
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-023.grafana.net
              auth:
                type: basic
                username: "1225361"
                password: "{{ grafana_password }}"