---
- name: Install Longhorn distributed storage for Kubernetes
  hosts: master
  tasks:
    - name: Check if open-iscsi is installed on nodes
      ansible.builtin.shell: |
        kubectl get nodes -o json | jq -r '.items[].status.nodeInfo.osImage'
      register: node_check
      changed_when: false

    - name: Apply iSCSI prerequisite installer DaemonSet
      ansible.builtin.shell: |
        kubectl apply -f {{ playbook_dir }}/templates/longhorn-iscsi-prereqs.yaml
      register: iscsi_install

    - name: Wait for iSCSI installation to complete
      ansible.builtin.shell: |
        kubectl -n kube-system wait --for=condition=ready pod -l app=longhorn-iscsi-installation --timeout=120s
      register: iscsi_wait
      ignore_errors: true

    - name: Remove iSCSI installer DaemonSet
      ansible.builtin.shell: |
        kubectl delete -f {{ playbook_dir }}/templates/longhorn-iscsi-prereqs.yaml
      when: iscsi_wait is succeeded

    - name: Add Longhorn Helm repository
      ansible.builtin.shell: |
        helm repo add longhorn https://charts.longhorn.io
        helm repo update
      register: helm_repo

    - name: Install Longhorn via Helm
      ansible.builtin.shell: |
        helm upgrade --install longhorn longhorn/longhorn \
          --namespace longhorn-system \
          --create-namespace \
          --version 1.6.0 \
          --set defaultSettings.defaultDataPath="/var/lib/longhorn" \
          --set defaultSettings.defaultReplicaCount=2
      register: longhorn_install

    - name: Wait for Longhorn to be ready
      ansible.builtin.shell: |
        kubectl -n longhorn-system wait --for=condition=ready pod -l app=longhorn-manager --timeout=300s
      register: wait_result

    - name: Verify Longhorn storage class
      ansible.builtin.shell: |
        kubectl get storageclass longhorn
      register: sc_result

    - name: Set Longhorn as default storage class
      ansible.builtin.shell: |
        kubectl patch storageclass longhorn -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
      register: default_sc

    - name: Get Longhorn UI access information
      ansible.builtin.shell: |
        echo "Longhorn UI can be accessed via port-forward:"
        echo "kubectl port-forward -n longhorn-system svc/longhorn-frontend 8080:80"
        echo "Then open http://localhost:8080"
      register: ui_info

    - name: Display installation summary
      ansible.builtin.debug:
        msg:
          - "Longhorn installation complete!"
          - "Storage class: {{ sc_result.stdout_lines }}"
          - "{{ ui_info.stdout_lines }}"
