---
- name: Install Longhorn distributed storage for Kubernetes
  hosts: master
  tasks:
    - name: Create temporary directory for manifests
      ansible.builtin.tempfile:
        state: directory
        suffix: longhorn
      register: tempdir

    - name: Create iSCSI prerequisite manifest
      ansible.builtin.copy:
        content: |
          apiVersion: apps/v1
          kind: DaemonSet
          metadata:
            name: longhorn-iscsi-installation
            namespace: kube-system
          spec:
            selector:
              matchLabels:
                app: longhorn-iscsi-installation
            template:
              metadata:
                labels:
                  app: longhorn-iscsi-installation
              spec:
                hostPID: true
                hostNetwork: true
                containers:
                - name: iscsi-installer
                  image: ubuntu:22.04
                  command:
                  - /bin/bash
                  - -c
                  - |
                    apt-get update
                    apt-get install -y open-iscsi nfs-common
                    systemctl enable iscsid || true
                    systemctl start iscsid || true
                    echo "iSCSI installation complete on $(hostname)"
                    sleep infinity
                  securityContext:
                    privileged: true
                  volumeMounts:
                  - name: host-root
                    mountPath: /host
                volumes:
                - name: host-root
                  hostPath:
                    path: /
        dest: "{{ tempdir.path }}/longhorn-iscsi-prereqs.yaml"

    - name: Apply iSCSI prerequisite installer DaemonSet
      ansible.builtin.shell: |
        kubectl apply -f {{ tempdir.path }}/longhorn-iscsi-prereqs.yaml
      register: iscsi_install

    - name: Wait for iSCSI installation to complete
      ansible.builtin.shell: |
        kubectl -n kube-system wait --for=condition=ready pod -l app=longhorn-iscsi-installation --timeout=120s
      register: iscsi_wait
      ignore_errors: true

    - name: Remove iSCSI installer DaemonSet
      ansible.builtin.shell: |
        kubectl delete -f {{ tempdir.path }}/longhorn-iscsi-prereqs.yaml
      when: iscsi_wait is succeeded

    - name: Add Longhorn Helm repository
      ansible.builtin.shell: |
        helm repo add longhorn https://charts.longhorn.io
        helm repo update
      register: helm_repo

    - name: Install Longhorn via Helm
      ansible.builtin.shell: |
        helm upgrade --install longhorn longhorn/longhorn \
          --namespace longhorn-system \
          --create-namespace \
          --version 1.6.0 \
          --set defaultSettings.defaultDataPath="/var/lib/longhorn" \
          --set defaultSettings.defaultReplicaCount=2
      register: longhorn_install

    - name: Wait for Longhorn to be ready
      ansible.builtin.shell: |
        kubectl -n longhorn-system wait --for=condition=ready pod -l app=longhorn-manager --timeout=300s
      register: wait_result

    - name: Wait for Longhorn storage class to be created
      ansible.builtin.shell: |
        for i in {1..30}; do
          if kubectl get storageclass longhorn &>/dev/null; then
            exit 0
          fi
          echo "Waiting for Longhorn storage class... attempt $i/30"
          sleep 10
        done
        exit 1
      register: sc_wait

    - name: Verify Longhorn storage class
      ansible.builtin.shell: |
        kubectl get storageclass longhorn
      register: sc_result

    - name: Set Longhorn as default storage class
      ansible.builtin.shell: |
        kubectl patch storageclass longhorn -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
      register: default_sc

    - name: Get Longhorn UI access information
      ansible.builtin.shell: |
        echo "Longhorn UI can be accessed via port-forward:"
        echo "kubectl port-forward -n longhorn-system svc/longhorn-frontend 8080:80"
        echo "Then open http://localhost:8080"
      register: ui_info

    - name: Display installation summary
      ansible.builtin.debug:
        msg:
          - "Longhorn installation complete!"
          - "Storage class: {{ sc_result.stdout_lines }}"
          - "{{ ui_info.stdout_lines }}"
