---
- name: Shutdown Worker Nodes
  hosts: worker
  become: true
  tasks:
    - name: Display shutdown warning for workers
      ansible.builtin.debug:
        msg: "Shutting down worker node: {{ inventory_hostname }}"

    - name: Shutdown worker nodes
      ansible.builtin.command: shutdown -h now
      async: 0
      poll: 0
      ignore_errors: true

- name: Wait for workers to shutdown
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 30 seconds for workers to shutdown
      ansible.builtin.pause:
        seconds: 30

- name: Shutdown Master Node
  hosts: master
  become: true
  tasks:
    - name: Display shutdown warning for master
      ansible.builtin.debug:
        msg: "Shutting down master node: {{ inventory_hostname }}"

    - name: Shutdown master node
      ansible.builtin.command: shutdown -h now
      async: 0
      poll: 0
      ignore_errors: true

- name: Wait for master to shutdown
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait 30 seconds for master to shutdown
      ansible.builtin.pause:
        seconds: 30

- name: Shutdown Console/Runner (localhost)
  hosts: localhost
  become: true
  tasks:
    - name: Display final shutdown warning
      ansible.builtin.debug:
        msg: "Shutting down console/runner in 5 seconds..."

    - name: Final pause before shutdown
      ansible.builtin.pause:
        seconds: 5

    - name: Shutdown console/runner
      ansible.builtin.command: shutdown -h now
      async: 0
      poll: 0
      ignore_errors: true
