- name: Deploy Eightbitsaxlounge Overlay on Kubernetes
  hosts: master
  tasks:
    - name: Ensure required environment variables are provided
      ansible.builtin.assert:
        that:
          - lookup('env','NAMESPACE') | length > 0
          - lookup('env','VERSION') | length > 0
        fail_msg: "Missing required env vars: NAMESPACE and/or VERSION. Ensure the workflow passes them to Ansible."

    - name: Determine Ingress Controller external IP (MetalLB)
      ansible.builtin.shell: |
        kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: ingress_ip_cmd
      changed_when: false

    - name: Compute overlay ingress host
      ansible.builtin.set_fact:
        overlay_ingress_host: >-
          {{ lookup('env','OVERLAY_INGRESS_HOST')
             | default(( (lookup('env','NAMESPACE') == 'eightbitsaxlounge-prod')
                        | ternary('overlay.', 'overlay-dev.') ) ~ ingress_ip_cmd.stdout ~ '.sslip.io', true) }}

    - name: Create a temporary directory for manifests
      ansible.builtin.tempfile:
        state: directory
        suffix: overlay-k8s
      register: tempdir

    - name: Copy deployment manifest to temp directory
      ansible.builtin.copy:
        src: k8s/deployment.yaml
        dest: "{{ tempdir.path }}/deployment.yaml"

    - name: Copy service manifest to temp directory
      ansible.builtin.copy:
        src: k8s/service.yaml
        dest: "{{ tempdir.path }}/service.yaml"

    - name: Template ingress manifest to temp directory
      ansible.builtin.template:
        src: k8s/ingress.yaml.j2
        dest: "{{ tempdir.path }}/ingress.yaml"
      vars:
        overlay_ingress_host: "{{ overlay_ingress_host }}"

    - name: Deploy Overlay Deployment
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/deployment.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Deploy Overlay Service
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/service.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Deploy Overlay Ingress
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/ingress.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Patch Deployment image to versioned tag
      ansible.builtin.shell: |
        IMAGE_BASE=${IMAGE_BASE:-ghcr.io/${GITHUB_REPOSITORY_OWNER}/eightbitsaxlounge-overlay}
        kubectl -n "$NAMESPACE" set image deploy/eightbitsaxlounge-overlay \
          overlay="${IMAGE_BASE}:${VERSION}"
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
        VERSION: "{{ lookup('env', 'VERSION') }}"
        GITHUB_REPOSITORY_OWNER: "{{ lookup('env', 'GITHUB_REPOSITORY_OWNER') | default('', true) }}"
        IMAGE_BASE: "{{ lookup('env', 'IMAGE_BASE') | default('', true) }}"

    - name: Annotate Deployment with change cause
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" annotate deploy/eightbitsaxlounge-overlay \
          kubernetes.io/change-cause="overlay ${VERSION}" --overwrite
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
        VERSION: "{{ lookup('env', 'VERSION') }}"

    - name: Wait for rollout to complete
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" rollout status deploy/eightbitsaxlounge-overlay --timeout=180s
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Verify running image
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" get deploy eightbitsaxlounge-overlay -o jsonpath='{.spec.template.spec.containers[0].image}'
      register: deploy_image
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Print running image
      ansible.builtin.debug:
        msg: "Deployment image: {{ deploy_image.stdout }}"

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent
