---
- name: Deploy Eightbitsaxlounge CouchDB on Kubernetes
  hosts: master
  tasks:
    - name: Ensure required environment variables are provided
      ansible.builtin.assert:
        that:
          - lookup('env','NAMESPACE') | length > 0
          - lookup('env','VERSION') | length > 0
        fail_msg: "Missing required env vars: NAMESPACE and/or VERSION. Ensure the workflow passes them to Ansible."

    - name: Determine Ingress Controller external IP (MetalLB)
      ansible.builtin.shell: |
        kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: ingress_ip_cmd
      changed_when: false

    - name: Compute db ingress host
      ansible.builtin.set_fact:
        db_ingress_host: >-
          {{ lookup('env','DB_INGRESS_HOST')
             | default(( (lookup('env','NAMESPACE') == 'eightbitsaxlounge-prod')
                        | ternary('db.', 'db-dev.') ) ~ ingress_ip_cmd.stdout ~ '.sslip.io', true) }}
    - name: Create a temporary directory for manifests
      ansible.builtin.tempfile:
        state: directory
        suffix: couchdb-k8s
      register: tempdir

    - name: Copy deployment manifest to temp directory
      ansible.builtin.copy:
        src: k8s/deployment.yaml
        dest: "{{ tempdir.path }}/deployment.yaml"

    - name: Copy PersistentVolumeClaim manifest to temp directory
      ansible.builtin.copy:
        src: k8s/persistentvolumeclaim.yaml
        dest: "{{ tempdir.path }}/persistentvolumeclaim.yaml"

    - name: Copy service manifest to temp directory
      ansible.builtin.copy:
        src: k8s/service.yaml
        dest: "{{ tempdir.path }}/service.yaml"

    - name: Template ingress manifest to temp directory
      ansible.builtin.template:
        src: k8s/ingress.yaml.j2
        dest: "{{ tempdir.path }}/ingress.yaml"
      vars:
        db_ingress_host: "{{ db_ingress_host }}"

    - name: Create CouchDB Secret
      ansible.builtin.shell: |
        kubectl create secret generic secret-db-couchdb \
          --from-literal=password=$COUCHDB_PASSWORD \
          --namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -
      environment:
        COUCHDB_PASSWORD: "{{ lookup('env', 'COUCHDB_PASSWORD') }}"
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Deploy CouchDB PersistentVolumeClaim
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/persistentvolumeclaim.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Deploy CouchDB Deployment
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/deployment.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Deploy CouchDB Service
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/service.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Deploy CouchDB Ingress
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/ingress.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Patch Deployment image to versioned tag
      ansible.builtin.shell: |
        IMAGE_BASE=${IMAGE_BASE:-ghcr.io/${GITHUB_REPOSITORY_OWNER}/eightbitsaxlounge-couchdb}
        kubectl -n "$NAMESPACE" set image deploy/eightbitsaxlounge-couchdb \
          couchdb="${IMAGE_BASE}:${VERSION}"
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
        VERSION: "{{ lookup('env', 'VERSION') }}"
        GITHUB_REPOSITORY_OWNER: "{{ lookup('env', 'GITHUB_REPOSITORY_OWNER') | default('', true) }}"
        IMAGE_BASE: "{{ lookup('env', 'IMAGE_BASE') | default('', true) }}"

    - name: Annotate Deployment with change cause
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" annotate deploy/eightbitsaxlounge-couchdb \
          kubernetes.io/change-cause="couchdb ${VERSION}" --overwrite
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
        VERSION: "{{ lookup('env', 'VERSION') }}"

    - name: Wait for rollout to complete
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" rollout status deploy/eightbitsaxlounge-couchdb --timeout=180s
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Verify running image
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" get deploy eightbitsaxlounge-couchdb -o jsonpath='{.spec.template.spec.containers[0].image}'
      register: deploy_image
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Print running image
      ansible.builtin.debug:
        msg: "Deployment image: {{ deploy_image.stdout }}"

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent