apiVersion: v1
kind: Secret
metadata:
  name: state-nats-creds
  labels:
    app: eightbitsaxlounge
    component: state
type: Opaque
data:
  # base encoded - usernames are in ConfigMap, secrets here are passwords only
  overlay_pass: placeholder
  chat_pass: placeholder
  midi_pass: placeholder
  data_pass: placeholder
