apiVersion: v1
kind: Secret
metadata:
  name: state-nats-creds
  labels:
    app: eightbitsaxlounge
    component: state
type: Opaque
data:
  # base encoded
  overlay_user: placeholder
  overlay_pass: placeholder
  ui_user: placeholder
  ui_pass: placeholder
  midi_user: placeholder
  midi_pass: placeholder
  data_user: placeholder
  data_pass: placeholder
