---
- name: Deploy Eightbitsaxlounge UI Chatbot on Kubernetes
  hosts: master
  tasks:
    - name: Ensure required environment variables are provided
      ansible.builtin.assert:
        that:
          - lookup('env','NAMESPACE') | length > 0
          - lookup('env','VERSION') | length > 0
          - lookup('env','TWITCH_CLIENT_ID') | length > 0
          - lookup('env','TWITCH_BOT_TOKEN') | length > 0
          - lookup('env','TWITCH_CHANNEL') | length > 0
          - lookup('env','MIDI_CLIENT_ID') | length > 0
          - lookup('env','MIDI_CLIENT_SECRET') | length > 0
        fail_msg: "Missing required environment variables. Ensure the workflow passes all required secrets."

    - name: Create a temporary directory for manifests
      ansible.builtin.tempfile:
        state: directory
        suffix: ui-k8s
      register: tempdir

    - name: Copy deployment manifest to temp directory
      ansible.builtin.copy:
        src: k8s/deployment.yaml
        dest: "{{ tempdir.path }}/deployment.yaml"

    - name: Create UI Secrets
      ansible.builtin.shell: |
        kubectl create secret generic eightbitsaxlounge-ui-secrets \
          --from-literal=client-id="$TWITCH_CLIENT_ID" \
          --from-literal=token="$TWITCH_BOT_TOKEN" \
          --from-literal=midi-client-id="$MIDI_CLIENT_ID" \
          --from-literal=midi-client-secret="$MIDI_CLIENT_SECRET" \
          --namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -
      environment:
        TWITCH_CLIENT_ID: "{{ lookup('env', 'TWITCH_CLIENT_ID') }}"
        TWITCH_BOT_TOKEN: "{{ lookup('env', 'TWITCH_BOT_TOKEN') }}"
        MIDI_CLIENT_ID: "{{ lookup('env', 'MIDI_CLIENT_ID') }}"
        MIDI_CLIENT_SECRET: "{{ lookup('env', 'MIDI_CLIENT_SECRET') }}"
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Create UI ConfigMap
      ansible.builtin.shell: |
        kubectl create configmap eightbitsaxlounge-ui-config \
          --from-literal=twitch_channel="$TWITCH_CHANNEL" \
          --from-literal=midi_device_url="$MIDI_DEVICE_URL" \
          --from-literal=log_level="$LOG_LEVEL" \
          --from-literal=bot_name="$BOT_NAME" \
          --namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -
      environment:
        TWITCH_CHANNEL: "{{ lookup('env', 'TWITCH_CHANNEL') }}"
        MIDI_DEVICE_URL: "{{ lookup('env', 'MIDI_DEVICE_URL') | default('http://midi-device-service.' ~ lookup('env', 'NAMESPACE') ~ '.svc.cluster.local:5000', true) }}"
        LOG_LEVEL: "{{ lookup('env', 'LOG_LEVEL') | default('INFO', true) }}"
        BOT_NAME: "{{ lookup('env', 'BOT_NAME') | default('', true) }}"
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Deploy UI Deployment
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/deployment.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Patch Deployment image to versioned tag
      ansible.builtin.shell: |
        IMAGE_BASE=${IMAGE_BASE:-ghcr.io/${GITHUB_REPOSITORY_OWNER}/eightbitsaxlounge-ui}
        kubectl -n "$NAMESPACE" set image deploy/eightbitsaxlounge-ui \
          twitch-bot="${IMAGE_BASE}:${VERSION}"
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
        VERSION: "{{ lookup('env', 'VERSION') }}"
        GITHUB_REPOSITORY_OWNER: "{{ lookup('env', 'GITHUB_REPOSITORY_OWNER') | default('', true) }}"
        IMAGE_BASE: "{{ lookup('env', 'IMAGE_BASE') | default('', true) }}"

    - name: Annotate Deployment with change cause
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" annotate deploy/eightbitsaxlounge-ui \
          kubernetes.io/change-cause="ui-chatbot ${VERSION}" --overwrite
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
        VERSION: "{{ lookup('env', 'VERSION') }}"

    - name: Wait for rollout to complete
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" rollout status deploy/eightbitsaxlounge-ui --timeout=180s
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Verify running image
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" get deploy eightbitsaxlounge-ui -o jsonpath='{.spec.template.spec.containers[0].image}'
      register: deploy_image
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Print running image
      ansible.builtin.debug:
        msg: "Deployment image: {{ deploy_image.stdout }}"

    - name: Get recent pod logs
      ansible.builtin.shell: |
        kubectl logs -n "$NAMESPACE" -l app=eightbitsaxlounge,component=ui --tail=20
      register: pod_logs
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
      ignore_errors: yes

    - name: Display recent logs
      ansible.builtin.debug:
        msg: "{{ pod_logs.stdout_lines }}"
      when: pod_logs.rc == 0

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent