---
- name: Deploy Eightbitsaxlounge UI Chatbot on Kubernetes
  hosts: master
  vars:
    # Service Configuration
    midi_service_url: "http://eightbitsaxlounge-midi-service:8080"
    
    # Kubernetes Configuration
    secret_name: "eightbitsaxlounge-ui-secrets"
    configmap_name: "eightbitsaxlounge-ui-config"
    deployment_name: "eightbitsaxlounge-ui"
    app_label: "eightbitsaxlounge"
    component_label: "ui"
    container_name: "twitch-bot"
    
    # Default Values
    default_twitch_channel: "the8bitsaxlounge"
    default_log_level: "INFO"
    default_image_base: "ghcr.io"
    
    # Deployment Configuration
    rollout_timeout: "180s"
    log_tail_lines: "20"
    
  tasks:
    - name: Ensure required environment variables are provided
      ansible.builtin.assert:
        that:
          - lookup('env','NAMESPACE') | length > 0
          - lookup('env','VERSION') | length > 0
          - lookup('env','TWITCH_CLIENT_ID') | length > 0
          - lookup('env','TWITCH_CLIENT_SECRET') | length > 0
          - lookup('env','MIDI_CLIENT_ID') | length > 0
          - lookup('env','MIDI_CLIENT_SECRET') | length > 0
        fail_msg: "Missing required environment variables. Ensure the workflow passes all required secrets."

    - name: Create a temporary directory for manifests
      ansible.builtin.tempfile:
        state: directory
        suffix: ui-k8s
      register: tempdir

    - name: Template deployment manifest to temp directory
      ansible.builtin.template:
        src: k8s/deployment.yaml
        dest: "{{ tempdir.path }}/deployment.yaml"

    - name: Template ConfigMap manifest to temp directory
      ansible.builtin.template:
        src: k8s/configmap.yaml
        dest: "{{ tempdir.path }}/configmap.yaml"

    - name: Apply UI ConfigMap (deploy what's in k8s/configmap.yaml)
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/configmap.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Create UI Secrets
      ansible.builtin.shell: |
        kubectl create secret generic {{ secret_name }} \
          --from-literal=client-id="$TWITCH_CLIENT_ID" \
          --from-literal=client-secret="$TWITCH_CLIENT_SECRET" \
          --from-literal=midi-client-id="$MIDI_CLIENT_ID" \
          --from-literal=midi-client-secret="$MIDI_CLIENT_SECRET" \
          --namespace $NAMESPACE \
          --dry-run=client -o yaml | kubectl apply -f -
      environment:
        TWITCH_CLIENT_ID: "{{ lookup('env', 'TWITCH_CLIENT_ID') }}"
        TWITCH_CLIENT_SECRET: "{{ lookup('env', 'TWITCH_CLIENT_SECRET') }}"
        MIDI_CLIENT_ID: "{{ lookup('env', 'MIDI_CLIENT_ID') }}"
        MIDI_CLIENT_SECRET: "{{ lookup('env', 'MIDI_CLIENT_SECRET') }}"
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Deploy UI Deployment
      ansible.builtin.shell: |
        kubectl apply -n $NAMESPACE -f {{ tempdir.path }}/deployment.yaml
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Patch Deployment image to versioned tag
      ansible.builtin.shell: |
        IMAGE_BASE=${IMAGE_BASE:-{{ default_image_base }}/${GITHUB_REPOSITORY_OWNER}/eightbitsaxlounge-ui}
        kubectl -n "$NAMESPACE" set image deploy/{{ deployment_name }} \
          {{ container_name }}="${IMAGE_BASE}:${VERSION}"
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
        VERSION: "{{ lookup('env', 'VERSION') }}"
        GITHUB_REPOSITORY_OWNER: "{{ lookup('env', 'GITHUB_REPOSITORY_OWNER') | default('', true) }}"
        IMAGE_BASE: "{{ lookup('env', 'IMAGE_BASE') | default('', true) }}"

    - name: Annotate Deployment with change cause
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" annotate deploy/{{ deployment_name }} \
          kubernetes.io/change-cause="ui-chatbot ${VERSION}" --overwrite
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
        VERSION: "{{ lookup('env', 'VERSION') }}"

    - name: Wait for rollout to complete
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" rollout status deploy/{{ deployment_name }} --timeout={{ rollout_timeout }}
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Verify running image
      ansible.builtin.shell: |
        kubectl -n "$NAMESPACE" get deploy {{ deployment_name }} -o jsonpath='{.spec.template.spec.containers[0].image}'
      register: deploy_image
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"

    - name: Print running image
      ansible.builtin.debug:
        msg: "Deployment image: {{ deploy_image.stdout }}"

    - name: Get recent pod logs
      ansible.builtin.shell: |
        kubectl logs -n "$NAMESPACE" -l app={{ app_label }},component={{ component_label }} --tail={{ log_tail_lines }}
      register: pod_logs
      environment:
        NAMESPACE: "{{ lookup('env', 'NAMESPACE') }}"
      ignore_errors: yes

    - name: Display recent logs
      ansible.builtin.debug:
        msg: "{{ pod_logs.stdout_lines }}"
      when: pod_logs.rc == 0

    - name: Remove temporary directory
      ansible.builtin.file:
        path: "{{ tempdir.path }}"
        state: absent